name: publish_codecov
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Generate + Publish Code Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # the arb files aren't under source control, generate them
      - name: Generate arb files
        run: dart run arb_generator
      - name: Install packages
        run: flutter pub get
      - name: Generate coverage helper
        run: sh bin/test_gather_all_files.sh messenger
      - name: Tests
        run: flutter test --coverage
      - name: Publish codecov report
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
